# Generated by Django 6.0.1 on 2026-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudent',
            name='document',
            field=models.CharField(max_length=110, unique=True),
        ),
    ]
